### ISSUE TITLE
[Home] 무비카드 section

### ISSUE THREAD

**Issue by namdaeun** [DOSOPT-CDS-WEB-4/CGV-Web-Client#11]
## 💚 어떤 기능인가요?
무비 카드를 선택하고, SelectTime 페이지로 넘어갈 수 있는 컴포넌트를 구현합니다.

## ✅ To Dos

- [x] 무비카드 생성
- [x] 무비카드 선택되면 background-color 변경
- [x] 무비카드 가로 스크롤 구현
- [x] 무비카드 하트 누르면 채워진 하트로 변경
- [x] 예매하기 버튼 누르면 데이터 전달
- [x] 예매하기 버튼 누르면 페이지 이동
- [x] section focus 이동

**Comment by Yeonseo-Jo** [comment]
UI 구현할 때는 더미데이터로 연습해보는걸 추천합니당 ~!

**Comment by namdaeun** [comment]
> UI 구현할 때는 더미데이터로 연습해보는걸 추천합니당 ~!

넵 꿀팁 감사해요🤩👍
