### ISSUE TITLE
[Home] my CGV 메뉴 카테고리 UI 구현

### ISSUE THREAD

**Issue by namdaeun** [DOSOPT-CDS-WEB-4/CGV-Web-Client#15]
## 💚 어떤 기능인가요?
my CGV를 포함한 마이페이지 카테고리를 구현합니다.

## ✅ To Dos

- [x] my CGV를 포함한 다른 메뉴들 생성
- [x] 해당 섹션만 흰색 배경이고 위 아래 다른 색상으로 구분되게 구현

**Comment by Yeonseo-Jo** [comment]
마이페이지가 -> 홍길동님, 진짜 안 본 영화가 없으시군요? 이 부분 맞나요?
맞다면, 제 기억으로는 이 부분은 데이터 통신 안하기로 했던것 같은데 한 번 더 확인 해 보기 !

**Comment by namdaeun** [comment]
> 마이페이지가 -> 홍길동님, 진짜 안 본 영화가 없으시군요? 이 부분 맞나요? 맞다면, 제 기억으로는 이 부분은 데이터 통신 안하기로 했던것 같은데 한 번 더 확인 해 보기 !

네 맞습니다! '더미데이터 만들어서 불러오기'라고 제가 메모를 남겨놓긴 했는데 후에 말이 바뀌었던 것 같기도 하네요!🧐 수정하겠습니다👍👍
