### ISSUE TITLE
[Home] 메뉴바 section

### ISSUE THREAD

**Issue by namdaeun** [DOSOPT-CDS-WEB-4/CGV-Web-Client#9]
## 💚 어떤 기능인가요?
메뉴 헤더(메뉴바) UI를 구현합니다.

## ✅ To Dos

- [x] 메뉴바 구현
- [x] 메뉴바 가로 스크롤

**Comment by Yeonseo-Jo** [comment]
메뉴바와 캐러셀 구현 이슈를 분리하는건 어떨까요 !
개인적으로는 둘이 분리 된 기능이기도 하고, 캐러셀이 꽤 구현이 필요한 부분일것 같아 분리하면 더 좋을것 같습니당 !!

**Comment by namdaeun** [comment]
> 메뉴바와 캐러셀 구현 이슈를 분리하는건 어떨까요 ! 개인적으로는 둘이 분리 된 기능이기도 하고, 캐러셀이 꽤 구현이 필요한 부분일것 같아 분리하면 더 좋을것 같습니당 !!

확실히 두 부분의 기능이 분리되어 있네요! 네 분리해서 따로 이슈 파겠습니다!!👍
